In [1]:
import pandas as pd
df=pd.read_csv("Combined_dataset.csv")

In [2]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [3]:
df.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
df.shape

(1000, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [9]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [10]:
df["discount"]=df["discount"].fillna(0)

In [13]:
df["seller_name"]=df["seller_name"].fillna("Unknown Seller")

In [36]:
df["seller_information"]=df["seller_information"].fillna("No Information")
df["variations"]=df["variations"].ffill()
df.drop("what_customers_said",axis=1)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,Sale
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Information Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Special Offer
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Information Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Information Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,Information Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,Limited Offer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",NaN,Information Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,Limited Offer
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Unknown Seller,"[{""size"":""Medium""}]",NaN,Information Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,Special Offer

In [37]:
df[(df["rating"]>=4.5) & (df["ratings_count"]>100)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,Sale
42,16696094,Van Heusen,Men Swift Dry High Stretch Mesh AIR Series Act...,4.6,192,649,0.0,"""₹649.00""",INR,http://assets.myntassets.com/assets/images/166...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,"Gro███ Fl███, N█████████old███████████████████...","[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs,No Sale
80,19103830,PUMA Motorsport,Unisex Black Perforations BMW MMS Neo Cat Regu...,4.5,157,6999,55.0,"""₹4,199.00""",INR,http://assets.myntassets.com/assets/images/191...,...,NaN,Sup███om ███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes,Mega Sale
143,10691426,SASSAFRAS,Black & Beige Ikat Print Cotton Shirt Dress,4.5,4441,2199,65.0,"""₹769.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"[{""percentage"":""79"",""value_name"":""Fit, Just Ri...",ARD███ Re███l C███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Khe███ No███76/█████████il ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,Mega Sale
211,10135431,Priyaasi,Green Gold-Plated Dome Shaped Jhumkas,4.5,347,1000,50.0,"""₹500.00""",INR,http://assets.myntassets.com/assets/images/101...,...,NaN,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]","[""rw-10135431_cae700""]",PRI███DES███S P█████████MIT███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings,Special Offer
422,21184968,HERE&NOW,Women Flared Heavy Fade Stretchable Jeans,4.6,111,2399,68.0,"""₹767.00""",INR,http://assets.myntassets.com/assets/images/211...,...,"[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,"11t███loo███Fla█████████6, ███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,Mega Sale
649,18903374,Levis,Women Blue Pure Cotton Casual Shirt,4.6,168,2599,45.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/189...,...,NaN,Vis███ St███,"[{""size"":""XS"",""value"":""35.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Special Offer
683,20071104,ADIDAS,Men Striped Amalgo M Running Shoes,4.5,149,4299,0.0,"""₹2,794.00""",INR,http://assets.myntassets.com/assets/images/200...,...,NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071104_cae700""]","1st███oor███abi█████████02,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,No Sale
687,20071402,ADIDAS,Men Rokr Trail Trekking Shoes,4.5,149,4599,0.0,"""₹4,599.00""",INR,http://assets.myntassets.com/assets/images/200...,...,NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071402_cae700""]","1st███oor███abi█████████02,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,No Sale
711,18906230,Skechers,Women Black GO WALK STRETCH FIT-SPECIAL D Shoes,4.5,127,7499,40.0,"""₹4,499.00""",INR,http://assets.myntassets.com/assets/images/189...,...,NaN,Sup███om ███,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,Special Offer
818,18639246,Jockey,Women Red Sleeveless Solid Tank Top,4.5,139,329,0.0,"""₹329.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""M"",""value"":""34.0in"",""value_name"":""Bu...",NaN,Information Not Available,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops,No Sale
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Mega Sale

In [32]:
df[["product_id","title","rating"]]

     product_id           title  rating
0       8376765     Lino Perros     3.8
1       9136281  Tommy Hilfiger     4.5
2      17633752           Lavie     4.4
3       1376949          F Gear     4.4
4      13939916       MYTRIDENT     4.7
..          ...             ...     ...
995    13698258           KREDO     3.5
996    16896006           GUESS     5.0
997     1708108        GIORDANO     2.8
998    19280114        Fastrack     4.3
999    18601682         BOLDFIT     3.8

[1000 rows x 3 columns]

In [33]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,Sale
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False

In [25]:
df.drop_duplicates(inplace=True)

In [27]:
df.shape

(1000, 24)

In [28]:
df["Sale"]=pd.cut(df["discount"],bins=[-1,0,20,50,100],labels=["No Sale","Limited Offer","Special Offer","Mega Sale"])

In [38]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,Sale
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Information Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Special Offer
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Information Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Information Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,Mega Sale
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,Information Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,Limited Offer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Information Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,NaN,Unknown Seller,"[{""size"":""Onesize""}]",NaN,Information Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,Special Offer
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,Limited Offer
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,Unknown Seller,"[{""size"":""Medium""}]",NaN,Information Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,Special Offer

In [39]:
df.to_csv("cleaned_dataset.csv")